### ISSUE TITLE
Package generator uses invalid path

### ISSUE THREAD

**Issue by alexbuzzbee** [atom/package-generator#27] opened 2015-06-25 21:20 UTC
The package generator appends `/my-project` to the projects home to generate the default package location, but then appends the path *again* when actually creating the package.

Creating the package
![atom-bug-1](https://cloud.githubusercontent.com/assets/2061796/8365892/6aeb3118-1b5e-11e5-8337-7a1d74d4f570.png)
Noticing the bug
![atom-bug-2](https://cloud.githubusercontent.com/assets/2061796/8365895/6eba567a-1b5e-11e5-8669-3ba1ffbf6b5a.png)

**Comment by alexbuzzbee** [comment] 2015-06-25 23:20
### Steps to reproduce

1. Open Atom 1.0.0.
2. Use the command palate or Packages menu (both cause the bug) to execute `Package Generator: Generate Atom Package`.
3. Replace the highlighted text with desired project name.
4. Check path in status bar.

### Expected result

Package generator would produce a new directory with the proper structure in `<canonical-projects-home-path>/<package-name>`.

### Actual result

Package generator created no directory and opened a new file at the supposed path `<canonical-projects-home-path>/<package-name>/<raw-projects-home-path>/<package-name>`.

**Comment by zeptonaut** [comment] 2015-06-30 13:50
I'm able to repro this locally as well (on Ubuntu 14.04).

This seems like a *really* major bug, given that Atom just went live and the package generator is used by just about all of the "create your own package" tutorials. This is going to be a major sticking point for new Atom users interested in playing around with creating their own packages.

**Comment by thomasjo** [comment] 2015-06-30 19:51
`~` is a Bash expansion, not an OS-level expansion as many users seem to think. The correct path in the original issue should be `/Users/alex/Documents/Git/my-package`.

I guess we should either correct the issue by "resolving" the tilde expansion, or validate entered paths and in this case, reject it.

**Comment by mnquintana** [comment] 2015-06-30 20:26
IMO we should expand `~` – I don't think we should put the onus on users to manually "expand" that `~` themselves when they want to use their home directory.

**Comment by zeptonaut** [comment] 2015-07-01 19:12
I don't think this problem is dependent on there being a tilde in the path: I encountered this problem when I tried to create a package at `/tmp/my-package` yesterday.

**Comment by thomasjo** [comment] 2015-07-02 12:57
> I don't think this problem is dependent on there being a tilde in the path: I encountered this problem when I tried to create a package at `/tmp/my-package` yesterday.

@zeptonaut I'm unable to reproduce. Are you sure you didn't mistype something? I just successfully created packages in both my user folder, and `/tmp`.

**Comment by izuzak** [comment] 2015-07-03 06:40
Yeah, I'm unable to reproduce this as well for a full path. I can reproduce the problem if the path contains a `~`, though.

**Closed** 2015-07-06 17:22 UTC
Labels: beginner, enhancement, linux, mac
